### ISSUE TITLE
Can I modify and use this in my repo?

### ISSUE THREAD

**Issue by ArjixWasTaken** [Qix-/cssquery#1]
This repo does not have any license attached, neither does the [pypi page](https://pypi.org/project/cssquery/)...(which also links to a [nonexistent github repo](https://github.com/bitlang/cssquery))
Will you allow me to modify and use your code in [my repo](https://github.com/ArjixWasTaken/PyML)?

**Comment by Qix-** [comment]
Go for it. If it works for you, consider it public domain or WTFPL or MIT, whichever best suits you. I don't remember making this 😅 so I can't guarantee it does anything useful! haha

Best of luck!

**Comment by ArjixWasTaken** [comment]
Thx!
